services:
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - ee-global-backend-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=skyvern
      - POSTGRES_PASSWORD=skyvern
      - POSTGRES_DB=skyvern
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skyvern"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    networks:
      - ee-global-backend-network
      - ee-global-frontend-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_STRING=postgresql+psycopg://skyvern:skyvern@postgres:5432/skyvern
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=true
      - LLM_KEY=OPENAI_GPT4O
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    networks:
      - ee-global-frontend-network
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - VITE_WSS_BASE_URL=wss://${VIRTUAL_HOST}/api/v1
      - VITE_API_BASE_URL=https://${VIRTUAL_HOST}/api/v1

networks:
  ee-global-frontend-network:
    external: true
  ee-global-backend-network:
    external: true

volumes:
  pg_data:
