version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    networks:
      - ee-global-backend-network
    # Uncomment if you want to externally connect to the DB:
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=skyvern
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    networks:
      - ee-global-backend-network
      - ee-global-frontend-network
    # Expose the API externally:
    ports:
      - "8000"
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
      # Uncomment to connect to local changes:
      # - ./skyvern:/app/skyvern
    environment:
      - DATABASE_STRING=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/skyvern
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=true
      - LLM_KEY=OPENAI_GPT4O
      - OPENAI_API_KEY=
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    networks:
      - ee-global-frontend-network
    # Expose the UI externally:
    ports:
      - "8080"
      - "9090"
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      - VITE_WSS_BASE_URL=ws://localhost:8000/api/v1
      # Uncomment and adjust if needed:
      # - VITE_ARTIFACT_API_BASE_URL=http://localhost:9090
      # - VITE_API_BASE_URL=http://localhost:8000/api/v1
      # - VITE_SKYVERN_API_KEY=
    depends_on:
      skyvern:
        condition: service_healthy

networks:
  ee-global-frontend-network:
    external: true
  ee-global-backend-network:
    external: true
