version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    networks:
      - ee-global-backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=skyvern
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    networks:
      - ee-global-backend-network
      - ee-global-frontend-network
    ports:
      - "8000"
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/skyvern
      - BROWSER_TYPE=chromium-headful
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      # - VIRTUAL_PORT=8000
      # Uncomment and configure your preferred LLM provider:
      # - ENABLE_OPENAI=true
      # - LLM_KEY=OPENAI_GPT4O
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    networks:
      - ee-global-frontend-network
    ports:
      - "8080"
      - "9090"
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      - VITE_API_BASE_URL=https://${VIRTUAL_HOST}/api/v1
      - VITE_WSS_BASE_URL=wss://${VIRTUAL_HOST}/api/v1
    depends_on:
      skyvern:
        condition: service_healthy

networks:
  ee-global-frontend-network:
    external: true
  ee-global-backend-network:
    external: true

volumes:
  postgres-data:
